<a href="https://colab.research.google.com/github/Pratham5321/Sentiment-Analysis/blob/main/sentiment%20analysis13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import libraries

In [22]:
#  Import required libraries

import pandas as pd
import numpy as np

#  Download the dataset

In [23]:
# download the dataset using the shell command (!wget : web get)

!wget https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Dataset.csv

--2026-05-07 13:20:18--  https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Dataset.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66212309 (63M) [text/plain]
Saving to: ‘IMDB-Dataset.csv.3’

IMDB-Dataset.csv.3  100%[===================>]  63.14M   166MB/s    in 0.4s

2026-05-07 13:20:19 (166 MB/s) - ‘IMDB-Dataset.csv.3’ saved [66212309/66212309]

In [24]:
# import the cvs file

df= pd.read_csv("IMDB-Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [25]:
# check the shape of the file

df.shape

(50000, 2)

- here is we have 2 columns and 50000 rows

In [26]:
# check for summary of dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [27]:
# check for imbalance
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64


- The Dataset is balanced

- also we have 2 categories

# Preprocessing

In [28]:
df["sentiment"]=df['sentiment'].map( {"positive":1, "negative" : 0})

In [29]:
# import the required libraries for processing

import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [30]:
# Tokenize

df["new_vector"]=df["review"].apply(word_tokenize)
df

,review,sentiment,new_vector
0,One of the other reviewers has mentioned that ...,1,"[One, of, the, other, reviewers, has, mentione..."
1,A wonderful little production. <br /><br />The...,1,"[A, wonderful, little, production, ., <, br, /..."
2,I thought this was a wonderful way to spend ti...,1,"[I, thought, this, was, a, wonderful, way, to,..."
3,Basically there's a family where a little boy ...,0,"[Basically, there, 's, a, family, where, a, li..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[Petter, Mattei, 's, ``, Love, in, the, Time, ..."
...,...,...,...
49995,I thought this movie did a down right good job...,1,"[I, thought, this, movie, did, a, down, right,..."
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[Bad, plot, ,, bad, dialogue, ,, bad, acting, ..."
49997,I am a Catholic taught in parochial elementary...,0,"[I, am, a, Catholic, taught, in, parochial, el..."
49998,I'm going to have to disagree with the previou...,0,"[I, 'm, going, to, have, to, disagree, with, t..."
49999,No one expects the Star Trek movies to be high...,0,"[No, one, expects, the, Star, Trek, movies, to..."

In [31]:
len(df["new_vector"][0])

380

In [32]:
# lowercasing

df["new_vector"]=df["new_vector"].apply(lambda x : [i.lower() for i in x] )
df

,review,sentiment,new_vector
0,One of the other reviewers has mentioned that ...,1,"[one, of, the, other, reviewers, has, mentione..."
1,A wonderful little production. <br /><br />The...,1,"[a, wonderful, little, production, ., <, br, /..."
2,I thought this was a wonderful way to spend ti...,1,"[i, thought, this, was, a, wonderful, way, to,..."
3,Basically there's a family where a little boy ...,0,"[basically, there, 's, a, family, where, a, li..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[petter, mattei, 's, ``, love, in, the, time, ..."
...,...,...,...
49995,I thought this movie did a down right good job...,1,"[i, thought, this, movie, did, a, down, right,..."
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[bad, plot, ,, bad, dialogue, ,, bad, acting, ..."
49997,I am a Catholic taught in parochial elementary...,0,"[i, am, a, catholic, taught, in, parochial, el..."
49998,I'm going to have to disagree with the previou...,0,"[i, 'm, going, to, have, to, disagree, with, t..."
49999,No one expects the Star Trek movies to be high...,0,"[no, one, expects, the, star, trek, movies, to..."

In [33]:
len(df["new_vector"][0])

380

In [34]:
# remove punctuation

df["new_vector"]=df["new_vector"].apply(lambda x: [i for i in x if i not in string.punctuation])
df

,review,sentiment,new_vector
0,One of the other reviewers has mentioned that ...,1,"[one, of, the, other, reviewers, has, mentione..."
1,A wonderful little production. <br /><br />The...,1,"[a, wonderful, little, production, br, br, the..."
2,I thought this was a wonderful way to spend ti...,1,"[i, thought, this, was, a, wonderful, way, to,..."
3,Basically there's a family where a little boy ...,0,"[basically, there, 's, a, family, where, a, li..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[petter, mattei, 's, ``, love, in, the, time, ..."
...,...,...,...
49995,I thought this movie did a down right good job...,1,"[i, thought, this, movie, did, a, down, right,..."
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,I am a Catholic taught in parochial elementary...,0,"[i, am, a, catholic, taught, in, parochial, el..."
49998,I'm going to have to disagree with the previou...,0,"[i, 'm, going, to, have, to, disagree, with, t..."
49999,No one expects the Star Trek movies to be high...,0,"[no, one, expects, the, star, trek, movies, to..."

In [35]:
len(df["new_vector"][0])

324

In [36]:
# remove the stopwords


stopword=stopwords.words("english")

df["new_vector"]=df["new_vector"].apply(lambda x: [i for i in x if i not in stopword])

df

,review,sentiment,new_vector
0,One of the other reviewers has mentioned that ...,1,"[one, reviewers, mentioned, watching, 1, oz, e..."
1,A wonderful little production. <br /><br />The...,1,"[wonderful, little, production, br, br, filmin..."
2,I thought this was a wonderful way to spend ti...,1,"[thought, wonderful, way, spend, time, hot, su..."
3,Basically there's a family where a little boy ...,0,"[basically, 's, family, little, boy, jake, thi..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[petter, mattei, 's, ``, love, time, money, ''..."
...,...,...,...
49995,I thought this movie did a down right good job...,1,"[thought, movie, right, good, job, n't, creati..."
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,I am a Catholic taught in parochial elementary...,0,"[catholic, taught, parochial, elementary, scho..."
49998,I'm going to have to disagree with the previou...,0,"['m, going, disagree, previous, comment, side,..."
49999,No one expects the Star Trek movies to be high...,0,"[one, expects, star, trek, movies, high, art, ..."

In [37]:
len(df["new_vector"][0])

182

In [38]:
# now we use the TFidvectorizer to convert the text data into the numbers

from sklearn.feature_extraction.text import TfidfVectorizer

df["clean_text"]=df["new_vector"].apply(lambda x : " ".join(x))
df

,review,sentiment,new_vector,clean_text
0,One of the other reviewers has mentioned that ...,1,"[one, reviewers, mentioned, watching, 1, oz, e...",one reviewers mentioned watching 1 oz episode ...
1,A wonderful little production. <br /><br />The...,1,"[wonderful, little, production, br, br, filmin...",wonderful little production br br filming tech...
2,I thought this was a wonderful way to spend ti...,1,"[thought, wonderful, way, spend, time, hot, su...",thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,0,"[basically, 's, family, little, boy, jake, thi...",basically 's family little boy jake thinks 's ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[petter, mattei, 's, ``, love, time, money, ''...",petter mattei 's `` love time money '' visuall...
...,...,...,...,...
49995,I thought this movie did a down right good job...,1,"[thought, movie, right, good, job, n't, creati...",thought movie right good job n't creative orig...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[bad, plot, bad, dialogue, bad, acting, idioti...",bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,0,"[catholic, taught, parochial, elementary, scho...",catholic taught parochial elementary schools n...
49998,I'm going to have to disagree with the previou...,0,"['m, going, disagree, previous, comment, side,...",'m going disagree previous comment side maltin...
49999,No one expects the Star Trek movies to be high...,0,"[one, expects, star, trek, movies, high, art, ...",one expects star trek movies high art fans exp...

In [39]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["clean_text"])

In [41]:
# now we split the data into the train and test set

y=df["sentiment"]

from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#  model training

In [43]:
# train the Logistic regression model

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

  # Model evaluation

In [45]:
# import evaluation libraries
from sklearn.metrics import accuracy_score , classification_report

In [48]:
# evaluate the test set

y_pred=model.predict(x_test)

print("accuracy Score : " ,accuracy_score(y_pred,y_test))
print()
print("classification report : \n",classification_report(y_pred,y_test))

accuracy Score :  0.8979

classification report :
               precision    recall  f1-score   support

           0       0.88      0.91      0.90      4812
           1       0.91      0.89      0.90      5188

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000

# Hyperparameter tuning

In [52]:
from sklearn.model_selection import GridSearchCV

logi_model=LogisticRegression( )

# creating a list of the parameters list

params={
    "C":[0.01,0.1,1.0],
    "penalty":["l1","l2"],
    "solver":["liblinear"]}

In [57]:
# train on the all possible pair of teh parameter

grid=GridSearchCV(
    logi_model,
    param_grid=params,
    cv=5,
    scoring="accuracy"
)

grid.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1.0], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear']},
             scoring='accuracy')

In [59]:
# best parameters


grid.best_params_

{'C': 1.0, 'penalty': 'l2', 'solver': 'liblinear'}

In [61]:
# best score

grid.best_score_

np.float64(0.8938750000000001)

In [71]:
# now we again train on the best parameters

logi_model=LogisticRegression(C= 1.0, penalty= 'l2', solver= 'liblinear')
logi_model.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [73]:
# evaluation

from sklearn.metrics import accuracy_score,classification_report


y_pred=logi_model.predict(x_test)

print("accuracy Score : " ,accuracy_score(y_pred,y_test))
print()
print("classification report : \n",classification_report(y_pred,y_test))

accuracy Score :  0.8983

classification report :
               precision    recall  f1-score   support

           0       0.88      0.91      0.90      4806
           1       0.91      0.89      0.90      5194

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000